FROM node:carbon

WORKDIR /usr/src/smart-brain-api

COPY ./ ./

RUN npm install

# RUN ./node_modules/.bin/testrpc&
# RUN ./node_modules/.bin/truffle compile
# RUN ./node_modules/.bin/truffle migrate

CMD ["/bin/bash"]