version: '3'

services: 
  smart-brain-api: 
    container_name: backend
#    image: node:carbon
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://root:1234@postgres:5432/smart-brain
      JWT_SECRET: JWT_SECRET
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api

  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
  
  redis:
    image: redis
    ports:
      - "6379:6379"
      
  geth:
    container_name: geth
    build: geth
    command: '--identity kalin --networkid 2017042099 --datadir "/root/.ethereum/devchain" --unlock 0,1 --password /root/.ethereum/devchain/pw --port "30303" --rpc --rpcport "8544" --rpccorsdomain "*" --rpcaddr="0.0.0.0" --rpcapi "admin,db,eth,miner,net,web3,personal,txpool" --nodiscover --minerthreads=2  --etherbase 0'
    ports:    
      - "8544:8544"
      - "30303:30303"
      - "30303:30303/udp"

  truffle:
    container_name: truffle
    build: truffle
    volumes:
      - ./dapp:/dapp
    ports:
      - "8080:8080"
      - "7000:8545"
    entrypoint: sh
    command: '-c "sleep 1d"'

  testrpc: # A very simple/light geth, only for testing purpose
    container_name: testrpc
    image: desmart/testrpc:latest
    ports:
      - "8545:8545"
